name: Adverse Event Model Training

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your desired Python version (e.g., '3.7')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements installation command if needed

    - name: Run Python script
      run: |
        python app.py

    - name: Save log file to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-log
        path: app.log
